version: '2'

services:

  filerundb:
    image: mariadb:latest
    container_name: filerun_db
    environment:
      MYSQL_ROOT_PASSWORD: filerunroot
      MYSQL_USER: filerun
      MYSQL_PASSWORD: filerun
      MYSQL_DATABASE: filerun
    volumes:
      - filerun_db:/var/lib/mysql
    networks:
      - internal

  filerun:
    image: afian/filerun
    container_name: filerun
    environment:
      FR_DB_HOST: filerundb
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun
      FR_DB_USER: filerun
      FR_DB_PASS: filerun
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - filerundb
    links:
      - filerundb:filerundb
    volumes:
      - filerun_html:/var/www/html
      - filerun_user_files:/user-files
    networks:
      - internal
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filerun.entrypoints=http"
      - "traefik.http.routers.filerun.rule=Host(`files.felted.de`)"
      - "traefik.http.middlewares.filerun-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.filerun.middlewares=filerun-https-redirect"
      - "traefik.http.routers.filerun-secure.entrypoints=https"
      - "traefik.http.routers.filerun-secure.rule=Host(`files.felted.de`)"
      - "traefik.http.routers.filerun-secure.tls=true"
      - "traefik.http.routers.filerun-secure.tls.certresolver=http"
      - "traefik.http.routers.filerun-secure.service=filerun"
      - "traefik.http.services.filerun.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    restart: unless-stopped

networks:
  internal:
    driver: bridge
  proxy:
    external:
      name: proxy

# Web: https://filerun.com/
# Docs: https://docs.filerun.com/
# Docker: https://hub.docker.com/r/afian/filerun
# GitHub: https://github.com/filerun/docker
