version: 2

services:
  teedy:
    image: sismics/docs:latest
    container_name: teedy
    volumes:
      - teedy_data:/data
    environment:
      DOCS_BASE_URL: https://docs.felted.de
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teedy.entrypoints=http"
      - "traefik.http.routers.teedy.rule=Host(`docs.felted.de`)"
      - "traefik.http.middlewares.teedy-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.teedy.middlewares=teedy-https-redirect"
      - "traefik.http.routers.teedy-secure.entrypoints=https"
      - "traefik.http.routers.teedy-secure.rule=Host(`docs.felted.de`)"
      - "traefik.http.routers.teedy-secure.tls=true"
      - "traefik.http.routers.teedy-secure.tls.certresolver=http"
      - "traefik.http.routers.teedy-secure.service=teedy"
      - "traefik.http.services.teedy.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external:
      name: proxy

# Teedy: https://teedy.io
# GitHub: https://github.com/sismics/docs
# Docker: https://hub.docker.com/r/sismics/docs