# Not used anymore
version: 2

services:
  wallabag:
    image: wallabag/wallabag
    container_name: wallabag
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=wall_db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=wallapass
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__LOCALE=de
      - SYMFONY__ENV__MAILER_HOST=127.0.0.1
      - SYMFONY__ENV__MAILER_USER=~
      - SYMFONY__ENV__MAILER_PASSWORD=~
      - SYMFONY__ENV__FROM_EMAIL=wallabag@example.com
      - SYMFONY__ENV__DOMAIN_NAME=https://bag.felted.de
    volumes:
      - wallabag_images:/var/www/wallabag/web/assets/images
    restart: unless-stopped
    networks:
      - proxy
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wallabag.entrypoints=http"
      - "traefik.http.routers.wallabag.rule=Host(`bag.felted.de`)"
      - "traefik.http.middlewares.wallabag-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.wallabag.middlewares=wallabag-https-redirect"
      - "traefik.http.routers.wallabag-secure.entrypoints=https"
      - "traefik.http.routers.wallabag-secure.rule=Host(`bag.felted.de`)"
      - "traefik.http.routers.wallabag-secure.tls=true"
      - "traefik.http.routers.wallabag-secure.tls.certresolver=http"
      - "traefik.http.routers.wallabag-secure.service=wallabag"
      - "traefik.http.services.wallabag.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

  wall_db:
    image: mariadb
    container_name: wallabag_db
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
    volumes:
      - wallabag_db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - internal

  redis:
    image: redis:alpine
    container_name: wallabag_redis
    volumes:
      - wallabag_redis_data:/data
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    driver: bridge
  proxy:
    external:
      name: proxy

