version: "2"

services:
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    # ports:
    #   - 80:80
    networks:
      - proxy
      - internal
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.entrypoints=http"
      - "traefik.http.routers.wordpress.rule=Host(`blog.felted.de`)"
      - "traefik.http.middlewares.wordpress-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.wordpress.middlewares=wordpress-https-redirect"
      - "traefik.http.routers.wordpress-secure.entrypoints=https"
      - "traefik.http.routers.wordpress-secure.rule=Host(`blog.felted.de`)"
      - "traefik.http.routers.wordpress-secure.tls=true"
      - "traefik.http.routers.wordpress-secure.tls.certresolver=http"
      - "traefik.http.routers.wordpress-secure.service=wordpress"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

  db:
    image: mysql:5.7
    restart: unless-stopped
    networks:
      - internal
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - wordpress_db:/var/lib/mysql

networks:
  internal:
    driver: bridge
  proxy:
    external:
      name: proxy

# Website: https://de.wordpress.com/
# GitHub: https://github.com/WordPress/WordPress
# Docker: https://hub.docker.com/_/wordpress